title: "NextGenPB Tutorial"
description: "A beginner-friendly guide to running and visualizing Poisson–Boltzmann simulations with NextGenPB."
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true

# Ordine di navigazione (facoltativo, per ordinare i file nel menu)
nav_sort: case_insensitive

# Per link relativi
markdown: kramdown
kramdown:
  input: GFM

extra_css:
  - assets/css/custom.css