title: "NextGenPB Tutorial"
description: "A beginner-friendly guide to running and visualizing Poisson–Boltzmann simulations with NextGenPB."
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true

nav_sort: case_insensitive

markdown: kramdown
kramdown:
  input: GFM

include:
  - assets/css

just_the_docs:
  custom_css:
    - assets/css/custom.css